---
name: YAML Check
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  lint-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yamllint
        run: |
          pip install yamllint
      - name: Lint YAML files recursively
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: '.yamllint.yaml'
